title: Maxwell's Blog
description: Data
author: Maxwell
github: https://github.com/nublu1234
about: Hello.
disqus_shortname: empty
google_analytics: UA-146810153-2

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/nublu1234"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/nublu1234"

share:
  twitter_username: nublu1234
  fb_appid:  # 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/all
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://nublu1234.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
